{
    "SessionId":10416132,
    "CinemaId":28,
    "Tickets": [
        {
        "AreaId":1,
        "IsComplimentary":false,
        "Barcode":null,
        "Children":[],
        "GiftCardAllowed":true,
        "IsUpgrade":false,
        "Surcharge":0,
        "Category":1,
        "TotalItemPrice":23.5,
        "MemberLimitPerSession":null,
        "Key":"ML06;2;;;",
        "ExcludedTicketIds":[],
        "IsRedemption":false,
        "Name":"Adult",
        "Code":"0024",
        "HOCode":"ML06",
        "Price":23.5,
        "MaxCount":10,
        "MinCount":1,
        "BookingFee":1.5,
        "SeatQty":1,
        "ScreenHelp":"\r\n<p>\r\n  An Adult ticket is required for people aged 16 or older unless a valid concession card discount is applicable\r\n</p>\r\n\r\n",
        "Featured":false,
        "PointsCost":null,
        "SoldOut":false,
        "PaymentRestrictions":[],
        "CreditCardRestrictions":[],
        "HideItem":false,
        "SortOrder":26,
        "IsTeaser":false,
        "Id":2,"Quantity":2,
        "RecognitionId":null}
    ],
    "GiftCards": [],
    "ConcessionItems": [],
    "MemberCards": [],
    "Seats": [
        {
            "Wheelchair":false,
            "CoupleSeat":false,
            "IsPlatinum":false,
            "Initials":null,
            "AreaId":1,"RelatedSeats":null,
            "Status":"Available",
            "SeatId":"0000000001|1|7|13",
            "SeatName":"H9",
            "index":163
        },
        {
            "Wheelchair":false,
            "CoupleSeat":false,
            "IsPlatinum":false,
            "Initials":null,
            "AreaId":1,
            "RelatedSeats":null,
            "Status":"Available",
            "SeatId":"0000000001|1|7|12",
            "SeatName":"H10","index":164
        }
    ],
    "PaymentTypeId": 3,
    "StoredCardId": null
}